name: finances
services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Finances
    ports:
      - '5432:5432'

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
